## Data Cleaning

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('shopping_behavior_updated.csv')

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

**Column Types:**
- **Numerical -** `Customer ID`,  `Age`,  `Purchase Amount (USD)`,  `Review Rating`,  `Previous Purchases` 
    
- **Categorical -** Remaining columns are Categorical columns

- **Mixed -** None — all columns shown are clearly numerical or categorical.

In [4]:
df.shape

(3900, 18)

In [5]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [6]:
# fix column names 
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [7]:
# Check
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [8]:
df.dtypes

customer_id                 int64
age                         int64
gender                        str
item_purchased                str
category                      str
purchase_amount             int64
location                      str
size                          str
color                         str
season                        str
review_rating             float64
subscription_status           str
shipping_type                 str
discount_applied              str
promo_code_used               str
previous_purchases          int64
payment_method                str
frequency_of_purchases        str
dtype: object

In [25]:
# check null values
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
age_group                 0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
# check invalid values
df['age'].between(18, 70).all()
df['purchase_amount'].between(20, 100).all()
df['review_rating'].between(1, 5).all()
df['previous_purchases'].ge(0).all()

np.True_

In [16]:
# check duplicate record
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

#### drop duplicate `promo_code_used` column
 it is not useful column

In [18]:
 df = df.drop(columns=['promo_code_used'])

## Feature engineering

In [19]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']

df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [20]:
df['age_group'].value_counts()

age_group
Young Adult    1028
Middle-aged     986
Senior          944
Adult           942
Name: count, dtype: int64

In [23]:
print(df.shape)
print(df.isnull().sum().sum())
print(df.duplicated().sum())

(3900, 18)
0
0

#### Save cleaned Data

In [24]:
df.to_csv('customer_behaviour_cleaned.csv', index=False)